### ISSUE TITLE
Remove redundant check in "WeatherForecast/NextDays" endpoint. To fix end of month bug

### ISSUE THREAD

**Issue by JorgenMU** [tiller-vgs/info-skjerm#73]
In the WeatherForcastController file remove this part of the code "nextDate != currentDate + dayIndexer ||" from :

 line 87: if (nextDate != currentDate + dayIndexer || nextHours != noon) continue;

And these two lines are redundant:

line 68: var currentDate = int.Parse(jsonElements.properties.timeseries[0].time.Substring(startIndex:8, length:2));

line 85: var nextDate = int.Parse(timeSeriesElement.time.Substring(startIndex: 8, length: 2));

**Comment by JorgenMU** [comment]
you can also remove redundant else statement on line 99

**Comment by Enderz420** [comment]
jon må accept pull request @JorgenMU
